### ISSUE TITLE
Semi-clone in (POSIX compatible) shell script

### ISSUE THREAD

**Issue by greduan** [adeel/timed#15]
Just thought I should let you know I made a semi-clone written in POSIX compatible shell script: https://gitlab.com/Greduan/scripts/raw/master/timer

Thanks for the inspiration. :) Timed is awesomely simple, but I don't like Python, so I made it in shell script.

It's a semi-clone because a feature is missing (parse), its outputs are different from timed's and by default it uses a directory local file (`./.timer`) instead of a global file (`$HOME/.timer`).

**Comment by adeel** [comment]
That's great!  Impressive that it can be done in so few lines of code.

**Comment by greduan** [comment]
Indeed. The shell's simplicity never ceases to amaze me.
